### ISSUE TITLE
lzma algorithm question

### ISSUE THREAD

**Issue by jinfeihan57** [nih-at/libzip#195]
I noticed that todo.md contains add lzma support. However, in the libzip source code, it seems that the lzma algorithm has been included. But it's all annotated. I release them and compiled without a problem. However, the files compressed by the libzip using the lzma algorithm cannot be decompressed by 7zip (7zip supports the zip+lzma format). I've done a [p7zip ](https://github.com/szcnick/p7zip)update and noticed that the lzma libraries used by 7zip and libzip are different. Check whether the format is incompatible due to this problem. Have you considered introducing the code for lzma in 7zip? If you don't introduce lzma in 7zip, do you have a solution? I'd like to contribute to this project. Do you have any suggestions?

**Comment by 0-wiz-0** [comment]
AFAIR we tested what you did (that's why the code fragments are there) but the lzma stream provided by the lzma library does not conform to the zip lzma specification.
We'd like to avoid having to include lzma code and would prefer to use the lzma library. If you find a way to get it to provide the lzma stream data in the correct way for zip, that'd be highly appreciated.
