### ISSUE TITLE
Invalid password is not correctly detected as ZIP_ER_WRONGPASSWD

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#209]
**Describe the Bug**

Open the provided `sample1.zip` archive:

```C++
zip_t * archive = zip_open("sample1.zip", ZIP_RDONLY, &error);
```

Set the default password to `"sample"`. (This password is actually incorrect.)

```C++
zip_set_default_password(archive, "sample");
```

Open the only file in the archive:

```C++
zip_file_t * file = zip_fopen_index(archive, 0, 0);
```

The file is successfully opened, despite the fact that it is encrypted and the provided password is incorrect.

Reading data from the file fails with `Zlib error: data error`

**Expected Behavior**

`zip_fopen_index()` fails with error `ZIP_ER_WRONGPASSWD`

**Observed Behavior**

`zip_fopen_index()` succeeds, but then reading data from the file fails with error `Zlib error: data error`.

**libzip Version**

a14fdedf

**Operating System**

Linux version 5.7.10 AMD64

**Test Files**
[sample1.zip](https://github.com/nih-at/libzip/files/5216178/sample1.zip)

**Additional context**

The correct password is `1234`.

**Comment by 0-wiz-0** [comment]
Yeah, I'm sorry, but the zip file format specification does not allow handling it better than this.
About 1-in-256 wrong passwords will be accepted and you might notice due to a Zlib data error (or not at all if you're extremely unlucky).
There is nothing libzip can do here, but I've documented it more explicitly now.
