### ISSUE TITLE
Consider "ulimit -n" on linux

### ISSUE THREAD

**Issue by szilardk** [nih-at/libzip#234]
**Description**
in case the number of zip files is bigger then "ulimit -n " then i get "Too many open files". in my test i have 2.000 small zip and have to merge them in one.

zipmerge 00_merge.zip *.zip                                                                         
zipmerge: can't open zip archive '84add508-5d37-4135-8b57-0a121b7ff807.zip': Can't open file: Too many open files

ulimit -n
1024

dpkg -l zipmerge
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version        Architecture Description
+++-==============-==============-============-=================================
ii  zipmerge       1.5.1-0ubuntu1 amd64        merge zip archives

**Solution**
- i was woundering if it would be possible that zipmerge adds zip files in batches not all of them at once

**Describe alternatives you've considered**
- an alternative is to increase the ulimit -n and this is working, but we do not always have access on the client systems.
- could merge 1000 every time and the results then together. this is an additional effort for the zipmerge client and if he does not have to do this could make zipmerge even better :-)

**Comment by dillof** [comment]
libzip needs to have access to all added files when it is writing out the new archive, which only happens when the merged archive is closed at the very end. We could add an option to have zipmerge add files in batches and call zip_commit after each batch, but that would essentially be the same as your second alternative method in that it would write the archive to disk multiple times.

**Comment by szilardk** [comment]
i am not sure how to intepret your answer. do you think it is better to work with alternative solutions (outside zipmerge) or are you considering adding something like this to zipmerge?
i would consider zipmerge more resilient if it would consider ulimit a. sure it might not be possible on all the platforms

**Comment by dillof** [comment]
I'm not sure myself yet.

I was mainly trying to describe what can be done. Making libzip able to handle more source archives than possible open file descriptors would be very hard with its current architecture.

Automatically handling that in zimperge in a portable way isn't easy either.

I'll have to think about it. But unless you are using a file system that supports cloning (macOS APFS or Linux btrfs), adding this to zipmerge won't be more efficient than doing it outside by calling zipmerge multiple times.

**Comment by szilardk** [comment]
i am not sure what did you mean with file system and cloning. could you elaborate on that?

**Comment by dillof** [comment]
Some filesystems support cloning a file. cloned files share the data blocks on disk, until one of them is changed, in which case the change data block is duplicated. That means copying is very fast. libzip supports this on macOS APFS and on Linux btrfs. 

For zipmerge that would mean that for each batch, the new data is appended to the old data (without having to copy the old data again), and then the new central directory is written. That would minimise the amount of data that needs to be written for each batch. If cloning is not available, the old data is copied to a new file, the new data and central directory appended to that. This is so that at any point, a valid version of the archive is available to avoid data loss incase of a program or system crash.

**Comment by dillof** [comment]
Upon further discussion, we decided that adding non-portable code to zipmerge is not worth it for this edge case. Please either raise the file descriptor limit, or call zipmerge multiple times.

We have documented this limitation in the man page.
