### ISSUE TITLE
Add function to check if zip_file_t supports seeking.

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#259]
**Describe the Bug**

After `zip_fseek` returned an error on compressed data, the `zip_file_t` object cannot be used anymore and `zip_fread` fails on it too.

**Expected Behavior**

When `zip_fseek` fails on compressed data, it shouldn't have any other side effect. The `zip_file_t` object should still be usable, and its position as reported by `zip_ftell` shouldn't have changed. Reading from the file using `zip_fread` should still work.

**Observed Behavior**

After `zip_fseek` returned an error on compressed data, the `zip_file_t` object cannot be used anymore and `zip_fread` fails on it too.

**libzip Version**

1.7.3.1

**Operating System**

Linux version 5.10.46

**Comment by dillof** [comment]
While I agree in principle, the way error handling in that part of libzip is implemented makes it hard.

I could add a function to check whether a `zip_file_t ` supports seeking, so you can avoid causing the error in the first place. Would that help?

**Comment by fdegros** [comment]
I don't think we need to add a new function for that.

At the moment, I use the following code to decide whether the file is _seekable_ or not:

```c++
struct zip_stat st = {};
const bool is_seekable = zip_stat_index(archive, id, 0, &st) == 0 &&
                         (st.valid & ZIP_STAT_COMP_METHOD) != 0 && 
                         st.comp_method == ZIP_CM_STORE;
```

Is this approach correct? So far, it seems to work. It doesn't seem too hard to determine whether a file is seekable or not.

So, what is preventing `zip_fseek` from quickly checking if it is acting on a compressed file and returning an error without modifying anything else?

**Comment by dillof** [comment]
Your approach may work currently, but it's not guaranteed to in the future. There is currently no public API that allows to check for this reliably.

The way error handling is implemented in libzip, we return `-1` to indicate an error occurred, and remember the actual error in the `zip_file_t` object. If an error has occurred, basically all subsequent operations on the object fail. To change this is non trivial, because some of the internal functions implementing the functionality rely on not being called again after an error.

That is why I suggested adding a function that checks whether a `zip_file_t` supports seeking, without actually trying to seek and thus causing an error.

**Comment by fdegros** [comment]
Thanks for the explanation. By the way, this error handling description would be useful to have in the documentation. This would help users getting a fitting mental model of the libzip error handling.

So yes, in that case, a function allowing to check if a `zip_file_t` is seekable without triggering an error would be useful.

**Comment by fdegros** [comment]
I just found out about `zip_file_error_clear`. Would it help in this case?

**Comment by dillof** [comment]
`zip_file_is_seekable()` has been added and will be part of the next release.
