### ISSUE TITLE
Filenames with invalid Windows NTFS characters

### ISSUE THREAD

**Issue by cmb69** [nih-at/libzip#263]
**Description**

This is about zip archives with filenames which contain invalid character for Windows NTFS (such as `*`). When these filenames are read by libzip, they are retrieved as is, but trying to extract these files to these filenames will obviously fail.

**Solution**

Tools like 7-zip internally mangle such filenames by replacing invalid characters with an underscore. libzip could do this as well.

**Describe alternatives you've considered**

This could also be handled by clients of libzip; this is why I've filed https://bugs.php.net/81488, but @remicollet suggested to ask here whether this might not better be solved by libzip in the first place.

**Comment by dillof** [comment]
libzip doesn’t extract files, it’s a library for manipulating zip archives and tries to be as platform agnostic as is reasonable.

As such, I don’t think libzip is the right place to handle this, since programs using libzip should be able to handle file names however they see fit, which might include not writing them to disk at all, replacing illegal characters, or asking the user to provide a valid file name instead.

Also, we don’t have the expertise nor the resources to implement and maintain file name mangling for every platform libzip can be used on.
