### ISSUE TITLE
Add support for XZ/LZMA compression

### ISSUE THREAD

**Issue by rthomsen** [nih-at/libzip#28]

**Comment by 0-wiz-0** [comment]
That is already a todo item. Are you planning on submitting a patch?

**Comment by gnfalex** [comment]
Patch for 1.5.2 (can't compile master branch due to https://github.com/nih-at/libzip/issues/111)
Compiled in MinGW-w64 with XZ 5.2.4, tested in MS Windows Vista x32.
7z 19.00 decompress zip+XZ succesfully - but with warning "Headers Error".
ziptool succesfully work with archives, created by  "7z a archive.zip -tzip -mm=xz files "
0001-Fix-BZip2-libs-location.patch  - for linking with libraries found with CMAKE Find_Package or pointed by ZLIB_LIBRARY / BZIP2_LIBRARIES

**Comment by gnfalex** [comment]
Sorry, looks like FF 52 have a great problems with attaching files and editing comments...
External link - https://drive.google.com/open?id=1duuFSBWnYBfzumGnyzJPKvAWulxcaxxq

**Comment by dillof** [comment]
Thanks for the patch, looks good on first glance. I'll have a closer look at it later.

**Comment by 0-wiz-0** [comment]
I've cleaned it up a bit and merged it. Thank you very much for your contribution!

LZMA/LZMA2 next? ;)
