### ISSUE TITLE
Forward slashes not enforced may loose directory info

### ISSUE THREAD

**Issue by ralfjunker** [nih-at/libzip#281]
libzip does not enforce forward '/' slashes in filenames as required by APPNOTE.TXT:
```
4.4.17 file name: (Variable)

       4.4.17.1 The name of the file, with optional relative path.
       The path stored MUST NOT contain a drive or
       device letter, or a leading slash.  All slashes
       MUST be forward slashes '/' as opposed to
       backwards slashes '\' for compatibility with Amiga
       and UNIX file systems etc.  If input came from standard
       input, there is no file name field.
```
Without this, archive managers may loose the folder structure if filenames contain backward slashes '\\', as common in Windows. 7-Zip does so, for example.

It could be argued that applications should replace backward with forward slashes. But I'd prefer the library to handle the replacement and create spec-conforming ZIP files only. It should also generate an error for drive letter or leading slash in filenames, as per above.

**Comment by dillof** [comment]
Backslashes are legal characters in Unix file names, and libzip can't know wether that is the case, or if its a Windows style file name and it should be a directory separator.

libzip should be usable in as many cases as possible, and if we forbid `\` in file names, we break valid use cases. The same goes for drive letters: `C:\file.txt` is a valid filename in Unix.

We could forbid leading slashes, but I'm not convinced it's worth the effort, especially since existing zip archives can contain file names with them, so users of libzip (or other tools handling zip archives) need to be able to deal with them anyway.

We will document these limitations, but otherwise libzip will remain as it is.

**Comment by dillof** [comment]
We have documented libzip's expectations regarding file names in libzip(3).
