### ISSUE TITLE
`zip_source_buffer_create` frees data even when `freed` is 0

### ISSUE THREAD

**Issue by robhz786** [nih-at/libzip#284]
**Describe the Bug**
buffer passed to `zip_source_buffer_create` is freed even when `freed` is 0, if `zip_file_add` is called.

**Expected Behavior**
The buffer should not be freed

**Observed Behavior**
It is

**To Reproduce**
Compile and execute the attached source file. It is the same as `examples/in-memory.c` of this repo, with basically two modifications:

1) Parameter `freed` passed `zip_source_buffer_create` is zero, and the passed buffer is manually deleted at the end of main. This works fine.

2) `modify_archive` function adds a file into the archive.
   This caused the buffer passed previously to `zip_source_buffer_create` to be deleted when `zip_close` is called, which later leads to a double delete ( when it is manually deleted ).

**libzip Version**
commit 34b13ca4e887a5aba050015e3a179069643f4e76
from Feb 4

**Operating System**
Ubuntu 20.04.03

**Test Files**
[in-memory.zip](https://github.com/nih-at/libzip/files/8050971/in-memory.zip)

**Comment by 0-wiz-0** [comment]
Can you please explain this some more?
In `modify_archive` you create a new buffer, since you don't pass a valid pointer, you can't free it.
In `main`you use two `data_*` and introduce some memory leaks (since you have to free `data_in` in all error cases now, and before overwriting it with `NULL`), but I'm not sure what you want to do there.
Are you saying that `data_in` is not valid any longer at the end of main even though you called `zip_source_buffer_create` with a `freep` argument of 0? How do you tell that that's the case?

**Comment by robhz786** [comment]
If this helps, the following steps in the debugger show the moment `data_in` is freed:

- add a breakpoint at `zip_close`
- when the program reaches there, add a breakpoint at `zip_source_buffer.c:218`
- The second time the programs hits this point, add a breakpoint at `zip_source_buffer.c:415` ( where the code does `free(buffer->fragments[i].data);` )
- When the program reaches there, print that address, you can see it is the same as `data_in`

NOTE: it doesn't happen if the zip archive already contains an "abc.txt" file.

**Comment by dillof** [comment]
Thank you for the report, I found the bug and fixed it.
