### ISSUE TITLE
Libzip issue with backslash

### ISSUE THREAD

**Issue by Kattabomane** [nih-at/libzip#291]
Hello,
I am using libzip for sevaral months whithout any issue.
Platform : Windows 2016/2019/10/11
Libzip version : 1.7.3
Few days before i discovered a problem when unzipping a zip file created with my tool (using libzip 1.7.3).
The unzipped folder does not contain  subfoders. Instead i got single level files separated by an odd character.
(see the capture below)
![image](https://user-images.githubusercontent.com/60187320/160347241-f1771a59-3273-4dc2-9f30-fa0365929de5.png)
It should be a folder tree like this :
DICOM \ PA20
DICOM \ PA20 \ ST29
....

After searching few hours, i reproduce the problem when using 7zip to uncompress.
7zip version 21 has this issue.
When searched for issue with 7zip i have been oriented that the issue is comming from the software which produces the zip.
I have then tryed to the latest version of libzip 1.8.0 and it has the same problem.

Have you ever seen this issue ?
Is there any workaround under libzip to avoid this problem ?

Thanks for your help.
K.

**Comment by dillof** [comment]
The zip file format uses `/` to separate directories, not `\` as is used on Windows. Since libzip is a platform agnostic library, and `\` can be used in file names on Unix and other operating systems, it is the responsibility of the program using libzip to make sure the file names it provides to libzip conform to this requirement. 

Which means that on Windows, you'll need to replace any `\` in a file name with `/` before passing it to libzip.

**Comment by Kattabomane** [comment]
Thanks for sharing your quick answer.
