### ISSUE TITLE
libzip 1.9.0 fails "make test" on macOS

### ISSUE THREAD

**Issue by pbobbenb** [nih-at/libzip#306]
**Describe the Bug**
libzip 1.9.0 fails "make test" on macOS 10.14.6.
These are the tests that fail:
         77 - name_locate-cp437.test (Failed)
	 78 - name_locate-utf8.test (Failed)
	133 - set_file_mtime_pkware.test (Failed)
	145 - unchange-delete-namelocate.test (Failed)

**Expected Behavior**
A successful "make test", as version 1.8.0 does.

**libzip Version**
1.9.0.

**Operating System**
macOS 10.14.6, Apple LLVM version 10.0.1 (clang-1001.0.46.4).

**Additional context**
Output from LastTest.log:
[LastTest.log.zip](https://github.com/nih-at/libzip/files/8995529/LastTest.log.zip)

**Comment by dillof** [comment]
The last two failures correspond to bugs we fixed in the last release, which makes me suspect, you inadvertently linked against an older version of libzip. Can you please check the output of `otool -L` against `ziptool_regress` in your build directory?

The first two could be related to locale settings in your environment. Our test suite tries to reset them to default values, and I just committed a change that made that more robust. Could you please try again with the latest git revision? If that still doesn't work, please send the output of `env`.

**Comment by pbobbenb** [comment]
Well, a make sudo install (with v1.9.0), make clean, make and make test and it passed all tests!

But why does it link it with the previous version in /usr/local/lib instead of the new version in build/lib?

This is link.txt from folder build/regress/CMakeFiles/ziptool_regress.dir
[link.txt](https://github.com/nih-at/libzip/files/9004845/link.txt)

**Comment by pbobbenb** [comment]
Found why it was linking with older version, I had changed @rpath to /usr/local/lib in lib/CMakeFiles/zip.dir/link.txt.

**Comment by 0-wiz-0** [comment]
Thanks for tracking this down!
