### ISSUE TITLE
compile error 	无法解析的外部符号 __imp__mktime64 

### ISSUE THREAD

**Issue by cucibala** [nih-at/libzip#317]
错误	LNK2001	无法解析的外部符号 __imp__mktime64 in zip.lib(zip_dirent.obj)

**Comment by dillof** [comment]
Please provide additional information, as requested in our compile error template:

Compiler Error
Output from the compiler, including exact and complete error message, file name and line number.

**libzip Version**
Version of libzip or revision repository used.

**Operating System and Compiler**
The operating system and compiler used, including version number.

Also, any flags passed to cmake.

**Autodetected Configuration**
Attach CmakeCache.txt from your build directory. This list everything cmake detected on your system.

**Additional context**
Add any other context about the problem here.

**Comment by cucibala** [comment]
我找到问题所在了，我使用CMake  编译的时候 设置的是 CMAKE_C_FLAGS_RELEASE /MD ，但是我实际的项目是 /MT。后来我将zlib.lib 的/MD 替换为 /MT, that's ok
