### ISSUE TITLE
Provide readahead or file offset calc function

### ISSUE THREAD

**Issue by uptycs-rmack** [nih-at/libzip#334]
I am working on an application that is reading zip files from high latency but high concurrency network attached storage. I would like to increase the throughput of my application by parallelizing IO for multiple files being read from within the same zip. I have implemented similar functionality for other file types by collecting the offsets of data I expect to read up front and issuing concurrent IO requests for them. After issuing all the read requests, when doing the sequential data processing, by the time I am done with the first file the remaining files have already loaded into the block cache and my operation runs without any additional IO stalls.

In order to do the same for the files in a zip, I need a way to know the starting offsets of data I will be reading inside the zip. A simple "give me the offset inside the zip to the start of the file header" function would be sufficient. Alternatively, a dedicated "zip_readahead_index" function that calls the linux readahead(2) syscall for the file would be fine too. If the file inside the zip is probably itself a zip (stored uncompressed and unencrypted), I would prefer to only read 128k or 256k bytes at the end of it to attempt to preload only the central directory.

I could build this using a thread pool making concurrent library calls on a single zip_t file however I am concerned that there is a risk of concurrency issues as the library is not meant to be used this way.

Any thoughts?

Thanks, Ryan

**Comment by uptycs-rmack** [comment]
Just for fun I tried the worker pool making concurrent file reads from the same zip_t and it went as poorly as expected.

**Comment by dillof** [comment]
Since readahead(2) blocks, calling it from within libzip wouldn't help, since libzip is single threaded.

We could provide you with the offset of the local header within the file. If you call zip_fopen(), it reads parts of the local header (to compute its size). Also, the file name and local extra field data need to be skipped, each of which can be up to 64k. Then the actual data starts. So even with this information, there is some imprecision.

Given all that and that this is a niche use case, we don't think it's worthwhile to add this to libzip. If you want to modify libzip locally, the field you're interested in is `entry[index].orig->offset`. Note that `orig` is `NULL` for newly added files.
