### ISSUE TITLE
How to map a version number to libzip.so number?

### ISSUE THREAD

**Issue by stuser81** [nih-at/libzip#369]
Inside lib/ I can see e.g. libzip.so.3 or libzip.so.4, depending on what version is installed.

* It's not obvious which libzip version maps to which so number. How to find these?
* Who decided these numbers - you, or the Linux distribution provider / the package manager repository provider?
* When is the number increased? I've noticed for many libraries the so number stays the same even if the library version increases.

* Debian 10/11 has this inside lib/:

```
libzip.so -> libzip.so.4
libzip.so.4 -> libzip.so.4.0
libzip.so.4.0
```
Would you expect the libzip .so files and symlinks to look exactly the same for **all Linux distributions** (assuming the compatibility version remains 4)? Is there any standard that Linux distributions should follow in this area?

**Comment by dillof** [comment]
> Inside lib/ I can see e.g. libzip.so.3 or libzip.so.4, depending on what version is installed.
> 
> * When is the number increased? I've noticed for many libraries the so number stays the same even if the library version increases.

There are clear criteria when a shared library number needs to be bumped:

- If you add symbols, you need to bump the minor version, since programs linking against the new version that use these symbols won't work with the old version.
- If you change or remove symbols, you need to bump the major version, since programs linking against the old version that use these symbols won't work with the new version.

We bump the shared library version according to these criteria. We don't bump it if none of these criteria apply.

We bump the libzip version for each release, patch (the third part) if the release consists of bug fixes only, minor (second part) if there are feature additions, and major (first) for major changes including backwards incompatibilities (which we strive to avoid).

> * It's not obvious which libzip version maps to which so number. How to find these?

There is no defined mapping. You could create a table of mappings by looking at the releases, but there is no way to predict mappings for future releases.

> * Who decided these numbers - you, or the Linux distribution provider / the package manager repository provider?
> * Debian 10/11 has this inside lib/:
> 
> ```
> libzip.so -> libzip.so.4
> libzip.so.4 -> libzip.so.4.0
> libzip.so.4.0
> ```
> 

We specify the number in lib/CMakeLists.txt, but packagers can override them for whatever reason they see fit.

> Would you expect the libzip .so files and symlinks to look exactly the same for **all Linux distributions** (assuming the compatibility version remains 4)? Is there any standard that Linux distributions should follow in this area?

I would never assume that anything is consistent across all Linux distributions. 

I don't know enough about Linux to know which standards/best practices exist.
