### ISSUE TITLE
File Data offset in Archive

### ISSUE THREAD

**Issue by saatvikshah1994** [nih-at/libzip#82]
Is it possible to find the offset in bytes of the data corresponding to a file in the archive from the start of the archive.
eg. dataset.zip
- 0.txt(offset: sizeof(localfileheader))
- 1.txt(offset: sizeof(localfileheader)*2 + sizeof(0.txt))
- 2.txt (offset:sizeof(localfileheader)*3 + sizeof(0.txt) + sizeof(1.txt))
...onwards

Given the above, is there anyway to obtain offset given the tuple ("dataset.zip", "1.txt")?

**Comment by dillof** [comment]
No, this is not supported. What would you need this information for?

**Comment by saatvikshah1994** [comment]
Hi @dillof , I have a very specific use case of a slightly complex stream processing workflow involving a data source of zst compressed files which have been zip archived. Passed in a tuple like above, I need to return the offset start position and file size ahead to another work-flow which performs an in-memory  decompression along with a few other things. <br>
I've been working with `ar` archives until now, but want to switch to zip with minimal changes on the code base and have thus been tinkering with libzip.

**Comment by dillof** [comment]
Reading directly from the underlying file is not supported by libzip, but you can read raw compressed data from a file in a zip archive by calling zip_fopen with the flag ZIP_FL_COMPRESSED. 

So you would need to adapt your next stage to read from a zip_file_t using zip_fread() instead of a FILE using fread(). You can get the file size via zip_stat(), using the member comp_size.
