### ISSUE TITLE
Make github release for 1.5.2

### ISSUE THREAD

**Issue by markaren** [nih-at/libzip#85]
This will allow us to update the [vcpkg port](https://github.com/Microsoft/vcpkg/blob/e9439ff5ca27c4d4ba43b33380f21933f32c61b7/ports/libzip/portfile.cmake)

**Comment by 0-wiz-0** [comment]
I just pushed the tag, sorry for forgetting that.

If you feel helpful, could you please take a look at the appveyor build and recommend fixes?
https://ci.appveyor.com/project/0-wiz-0/libzip

The arm builds stopped working a long time ago I think because something changed in the vcpkg infrastructure. Recently also the other builds broke.

**Comment by markaren** [comment]
Mhh, not sure if I help much with that particular problem.
Anyway, I've pushed a PR for libzip to vcpkg: https://github.com/Microsoft/vcpkg/pull/5656

**Comment by markaren** [comment]
Mhh, yeah. vcpkg fails installing 1.5.2..

**Comment by 0-wiz-0** [comment]
Try https://github.com/nih-at/libzip/commit/1e6b758ad1284736c681e55a9d5315c0e79dd92f

**Comment by markaren** [comment]
That did the trick :)

**Comment by 0-wiz-0** [comment]
Great, thanks for testing.

**Comment by markaren** [comment]
Will you make a patch release that I can use for the vcpkg port?

**Comment by 0-wiz-0** [comment]
No, please include the patch manually.
