### ISSUE TITLE
Progress callback for zip_open

### ISSUE THREAD

**Issue by mazen-mardini** [nih-at/libzip#92]
Hello!

There is a way to set a progress callback for zip_close with zip_register_progress_callback_with_state. However there is no way to do the same for zip_open.

A suggestion is to have something similar to that for zip_open, as zip_open may take noticeable time to complete if the ZIP-file is large.

**Comment by dillof** [comment]
The callback would need to be an argument to zip_open, since there is no struct yet to register it with. And I really don't want to introduce yet another zip_open variant.

Also, for some strange zip archives, it would be hard to report accurate progress: there might be data that looks like a central directory in uncompressed file data or the archive comment .
